// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "firstInstall": boolean;
      "apiBase": string;
      "uid": string;
      "token": string;
      "accessMode": string;
      "defaultEmail": string;
      "autoRequestFullText": boolean;
      "downloadEngine": string;
      "autoDownloadOnAdd": boolean;
      "scihubUrls": string;
      "agentMailEnabled": boolean;
      "agentMailCliPath": string;
      "agentMailSenderFilter": string;
      "agentMailDir": string;
      "agentMailPollLimit": number;
      "agentMailLastMessageId": string;
      "mailBackend": string;
      "pop3Host": string;
      "pop3Port": number;
      "pop3UseSSL": boolean;
      "pop3Username": string;
      "pop3Password": string;
      "agentMailRefreshMinutes": number;
      "powerShellPath": string;
      "cmdPath": string;
      "agentMailMatchMode": string;
    };
  }
}
